tap 'homebrew/science'
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/dupes'

# Install command line apps

brew 'ack'
brew 'ansiweather'
brew 'archey'
brew 'bash'
brew 'ccat'
brew 'coreutils'
brew 'curl'
brew 'diff-so-fancy'
brew 'duti'
brew 'ffmpeg'
brew 'findutils'
brew 'gcc'
brew 'git'
brew 'git-extras'
brew 'git-flow'
brew 'git-lfs'
brew 'gist'
brew 'graphviz', args: ['with-bindings', 'with-librsvg']
brew 'htop'
brew 'hub'
brew 'imagemagick', args: ['with-librscg']
brew 'lastpass-cli'
brew 'libsvg'
brew 'libxml2'
brew 'media-info'
brew 'moreutils'
brew 'multimarkdown'
brew 'nano'
brew 'octave', args: ['with-docs', 'with-openblas']
brew 'pacvim'
brew 'pandoc'
brew 'pandoc-citeproc'
brew 'pkg-config'
brew 'r', args: ['with-openblas']
brew 'rclone'
brew 'ssh-copy-id'
brew 'sshfs'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'tmux'
brew 'vim', args: ['with-override-system-vi', 'with-python3']
brew 'wget'
brew 'youtube-dl'
brew 'z'
brew 'zeromq'
# For Bash or Zsh, put something like this in your $HOME/.bashrc or $HOME/.zshrc:
#   . `brew --prefix`/etc/profile.d/z.sh
brew 'zsh', args: ['with-texi2html'] 


# dupes
brew 'grep', args: ['with-default-names']
brew 'lsof'
brew 'nano'
brew 'rsync'
brew 'screen'
brew 'units'
brew 'whois'

cask_args appdir: '/Applications'
cask 'alfred'
cask 'bartender'
cask 'bettertouchtool'
cask 'caffeine'
cask 'cheatsheet'
cask 'dash'
cask 'dropbox'
cask 'flux'
cask 'google-chrome'
cask 'google-drive'
cask 'google-play-music-desktop-player'
cask 'iterm2'
cask 'java'
cask 'kindle'
cask 'macdown'
cask 'mactex'
cask 'macvim'
cask 'material-colors'
cask 'miniconda'
cask 'monodraw'
cask 'kodi'
cask 'rodeo'
cask 'rstudio'
cask 'sidestep'
cask 'skim'
cask 'slack'
cask 'sourcetree'
cask 'spectacle'
cask 'steam'
cask 'sublime-text'
cask 'texstudio'
cask 'trim-enabler'
cask 'the-unarchiver'
cask 'vlc'
#  cask 'xquartz'

# Fonts
cask 'font-fira-code'
cask 'font-dejavu-sans'
cask 'font-source-code-pro'
cask 'font-hack'

# QuickLook
cask 'qlmarkdown'
cask 'qlcolorcode'
cask 'qlprettypatch'
cask 'qlimagesize'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'jupyter-notebook-ql'

