name: main
channels: 
    - conda-forge
    - defaults
dependencies:
    - python=3.5
    - cython
    - jupyter
    - numpy
    - matplotlib
    - seaborn
    - networkx
    - scipy
    - pandas
    - scikit-learn
    - nltk
    - gensim
    - statsmodels
    - pytest
