name: main
channels: 
    - defaults
    - conda-forge
dependencies:
    - python>3.6
    - numpy
    - scipy
    - pandas
    - jupyter
    - matplotlib
    - seaborn
    - scikit-learn
    - nltk
    - pytest
    - sympy
    - graphviz
    - pandocfilters
    - cython
    - numba
